[package]
name = "graph_vis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.26"
eframe = "0.26"
petgraph = "0.6"
rand = "0.8.5"
egui_graphs = "0.18.0"
